---
abstract: 'Run cleanup code after request completion'
author:
  - 'Hans Dieter Pearcey <hdp@pobox.com>'
build_requires:
  HTTP::Request::Common: 0
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0.87_01
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Cleanup
no_index:
  package:
    - Plack::Middleware::Cleanup::Guard
requires:
  Plack::Middleware: 0
  parent: 0
  strict: 0
  warnings: 0
version: 0.002
